export const routes = [
  {
    id: "dashboard",
    path: "/dashboard",
    file: "dashboard.html",
    label: "แดชบอร์ด",
    subtitle: "ภาพรวมสถิติและข้อมูลทั้งหมดในระบบ",
    icon: "fa-chart-pie",
  },
  {
    id: "admin",
    path: "/admin",
    file: "admin",
    label: "ผู้ดูแลระบบ",
    subtitle: "จัดการผู้ใช้งานและตั้งค่าระบบ",
    icon: "fa-user-shield",
    adminOnly: true,
    hidden: true,
  },
  {
    id: "admin-settings",
    path: "/admin/settings",
    label: "ตั้งค่าระบบ",
    subtitle: "กำหนดค่าเริ่มต้น",
    icon: "fa-cogs",
    adminOnly: true,
  },
  {
    id: "subjects",
    path: "/subjects",
    file: "subjects.html",
    label: "รายวิชาและกลุ่มเรียน",
    subtitle: "จัดการข้อมูลรายวิชาและกลุ่มเรียนที่เปิดสอน",
    icon: "fa-book-open",
  },
  {
    id: "students",
    path: "/students",
    file: "students.html",
    label: "รายชื่อผู้เรียน",
    subtitle: "เพิ่มและแก้ไขข้อมูลผู้เรียนในระบบ",
    icon: "fa-user-graduate",
  },
  {
    id: "exams",
    path: "/exams",
    file: "exams.html",
    label: "กระดาษคำตอบ",
    subtitle: "สร้างกระดาษคำตอบและพิมพ์กระดาษคำตอบ",
    icon: "fa-file-pen",
  },
  {
    id: "answer-key",
    path: "/answer-key",
    file: "answer-key.html",
    label: "เฉลยข้อสอบ",
    subtitle: "ตั้งค่าเฉลยและเกณฑ์การให้คะแนน",
    icon: "fa-key",
    hidden: true,
  },
  {
    id: "results",
    path: "/results",
    file: "results.html",
    label: "ผลการสอบ",
    subtitle: "ดูคะแนนและตรวจสอบความถูกต้องของกระดาษคำตอบ",
    icon: "fa-square-poll-vertical",
  },
  {
    id: "analysis",
    path: "/analysis",
    file: "analysis.html",
    label: "วิเคราะห์ผล",
    subtitle: "วิเคราะห์ความยากง่ายและคุณภาพของข้อสอบ",
    icon: "fa-chart-line",
  },
  {
    id: "reports",
    path: "/reports",
    file: "reports.html",
    label: "รายงานผล",
    subtitle: "พิมพ์รายงานสรุปผลการสอบ",
    icon: "fa-file-invoice",
  },
  {
    id: "answer-sheet",
    path: "/answer-sheet",
    file: "answer_sheet.html",
    label: "กระดาษคำตอบ",
    subtitle: "พิมพ์แบบฟอร์มกระดาษคำตอบ",
    icon: "fa-file-lines",
    hidden: true,
  },
];

export const legacyRouteMap = Object.fromEntries(
  routes.map((route) => [route.file, route.id]),
);

export const routeById = Object.fromEntries(
  routes.map((route) => [route.id, route]),
);
